# Generated by Django 5.0.3 on 2024-04-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_search_service', '0001_initial'),
    ]

    operations = [
    ]
