# Generated by Django 5.0.3 on 2024-04-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_search_service', '0002_auto_20240406_1407'),
    ]

    operations = [
    ]
