# Generated by Django 5.0.3 on 2024-04-05 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_search_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train_search_service.train')),
            ],
        ),
    ]
