# Generated by Django 5.0.3 on 2024-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_schedule_service', '0002_train_trainschedule_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainschedule',
            name='departure_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
