# Generated by Django 5.0.3 on 2024-04-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_schedule_service', '0003_alter_trainschedule_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainschedule',
            name='destination',
        ),
        migrations.AddField(
            model_name='train',
            name='route_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='route_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='route',
            field=models.CharField(default='', max_length=50),
        ),
    ]
