# Generated by Django 5.0.3 on 2024-04-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_schedule_service', '0004_remove_trainschedule_destination_train_route_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainschedule',
            name='start_location',
        ),
    ]
