# Generated by Django 5.0.3 on 2024-04-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_schedule_service', '0005_remove_trainschedule_start_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_tag',
        ),
    ]
