# Generated by Django 5.0.3 on 2024-04-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_booking_service', '0001_initial'),
        ('train_schedule_service', '0008_train_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='train',
        ),
        migrations.AddField(
            model_name='seat',
            name='block_letter',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='seat',
            name='schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='train_schedule_service.trainschedule'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
