# Generated by Django 5.0.3 on 2024-04-08 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_booking_service', '0003_remove_seat_block_letter_remove_seat_is_booked_and_more'),
        ('train_schedule_service', '0008_train_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_schedule_service.trainschedule'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
